name: Update cantine.xml

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - run: pip install requests beautifulsoup4

      - run: python generate_rss.py

      - run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "github-actions"
          git add cantine.xml
          git diff --quiet || git commit -m "update rss"

      - run: git push
